[package]
name = "pvlc-pack"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
blake3.workspace = true
pvlc-ir = { path = "../pvlc-ir" }
pvlc-model-schema = { path = "../pvlc-model-schema" }
pvlc-runtime-core = { path = "../pvlc-runtime-core" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
pvlc-cpu-ref = { path = "../pvlc-cpu-ref" }
pvlc-safetensors = { path = "../pvlc-safetensors" }
pvlc-testkit = { path = "../pvlc-testkit" }
